### ISSUE TITLE
Vergleichen von Zeichenketten

### ISSUE THREAD

**Issue by Michelle-Createment** [Elena-Cloud-Star/Modul2#2]
Bitte die Aufgabenstellungen unter den jeweiligen Kommentaren bearbeiten :) 
In der Aufgabenstellung Vergleichen von Zeichenketten z.B. hast du ausversehen eine Teilaufgabe unter Suchen geschrieben :)

**Comment by Elena-Cloud-Star** [comment]
ja, hab auch schon gemerkt)))) danke)
